### ISSUE TITLE
i18n.translate fails on non-string values

### ISSUE THREAD

**Issue by arthot** [skolmer/es2015-i18n-tag#58]
Hi!

It seems like `translate` function lacks of type safety. For instance the following code `i18n.translate(null)` or  `i18n.translate(10)` produces error
```
    TypeError: Cannot read property 'replace' of null
    TypeError: str.replace is not a function

      355 |     // e.g. this._formatStrings('{0} {1}!', 'hello', 'world') == 'hello world!'
      356 |     _buildMessage(str, ...values) {
    > 357 |         return str.replace(/\${(\d)}/g, (_, index) => values[Number(index)])
      358 |     }
      359 | }
      360 | 
```

I think it's not desired behaviour and this method should treat undefined/null as empty string and convert anything else to string. But of course this behaviour is discussable. I preprepared a PR based on that behaviour assumption.

**Comment by skolmer** [comment]
Hi @arthot ,

thanks for the PR. I agree, translate should work with non string values. But should we convert null/undefined to an empty string or throw an error or just return the original value? My argument would be that null or undefined are unexpected input values for `translate()` because the translation key is an required argument, therefore it should throw an exception. This would help debugging those cases where you accidentally assign the wrong variable as translation key. What do you think?

**Comment by arthot** [comment]
The problem with throwing an error in runtime is usually a not desired behaviour from "utils" library. Moreover this PR was made exactly for that one particular reason - prevent React render function from crashes. We have already encountered this error in production a few times before and every fix was exactly `var || ''` because sometimes it's too hard to control exact type inside variable. It could be null or undefined. So I believe throwing an error here won't change a lot, but swallowing null will save someone's night from deploying a hotfix. But maybe accepting non-primitive types is too much

**Comment by skolmer** [comment]
Released in https://github.com/skolmer/es2015-i18n-tag/releases/tag/v1.5.0

**Comment by skolmer** [comment]
@all-contributors please add @arthot for infrastructure, tests and code
