### ISSUE TITLE
es2015-i18n-tag@1.6.2 package broken

### ISSUE THREAD

**Issue by nor3** [skolmer/es2015-i18n-tag#71]
latest package does not contain dist folder so load module failed.

```bash
# npm install es2015-i18n-tag
+ es2015-i18n-tag@1.6.2
added 1 package from 1 contributor in 0.944s
# cd node_modules/es2015-i18n-tag/
# ls -lR
.:
total 272
-rw-r--r--. 1 root root   5268 Jan 19 22:15 benchmark.js
-rw-r--r--. 1 root root      0 Jan 19 22:15 CHANGELOG.md
-rw-r--r--. 1 root root   2528 Jan 19 22:15 CONTRIBUTING.md
-rw-r--r--. 1 root root   1081 Jan 19 22:15 LICENSE
-rw-r--r--. 1 root root   4469 Jan 20 14:00 package.json
-rw-r--r--. 1 root root  20006 Jan 19 22:15 README.md
-rw-r--r--. 1 root root 233307 Jan 19 22:15 yarn.lock
```

**Comment by skolmer** [comment]
Thanks for reporting. Not sure what went wrong. For now you can use v1.6.1. I will look into it when I find some time.

**Comment by skolmer** [comment]
I have set the package version to deprecated.

**Comment by AndyOGo** [comment]
@skolmer Within 24 hours you could have removed this version from NPM, guess is too late now.

And I guess deprecation is misleading, NPM says this package has been deprecated, not that version...

<img width="1062" alt="Screenshot 2020-01-20 at 23 39 03" src="https://user-images.githubusercontent.com/914443/72762155-d0cb8a00-3bde-11ea-8779-f2602ec91c9b.png">

**Comment by skolmer** [comment]
@AndyOGo  I have deprecated the specific version of this package via npm cli. You can see it in the version history if you set deprecated versions to visible. 
Do you mean using unpublish command? I'm not sure what would have been the best procedure in a case like this. My intention was to avoid that other users are auto migrating to this broken package because of a patch version rule. I went by the recommendations of npm documentation: 
> It is generally considered bad behavior to remove versions of a library that others are depending on!

**Comment by skolmer** [comment]
Wee need better scripts/testing to avoid f***ups like this #72

**Comment by AndyOGo** [comment]
@skolmer 
Yeah that's right, in general packages shouldn't be removed.
`left-pad` has shown what can happen...
https://qz.com/646467/how-one-programmer-broke-the-internet-by-deleting-a-tiny-piece-of-code/

But I would argue, since this version isn't working at all and `unpublish` allows you to target specific versions it would have been the better choice, cause caret instalations like `^1.6.1` will always pull `1.6.2` until it is replaced.

Btw. I have to correct myself, you can unpublish within 72 hours:
> With the default registry (registry.npmjs.org), `unpublish` is only allowed with versions published in the **last 72 hours**. If you are trying to `unpublish` a version published longer ago than that, contact support@npmjs.com.
https://docs.npmjs.com/cli/unpublish

**Comment by skolmer** [comment]
Ok, I can follow that argumentation. I have now **unpublished** this package version. I had the impression that semver caret handling will exclude deprecated versions but couldn't find any documentation on that. So now everyone should be safe from getting a broken package.

**Comment by AndyOGo** [comment]
Great, just keep in mind, that you can't reuse that version number `1.6.2`.

> Even if a package version is unpublished, that specific name and version combination can never be reused. In order to publish the package again, a new version number must be used. 
https://docs.npmjs.com/cli/unpublish#description
